import React, { useState } from 'react';
import Head from 'next/head';
import { createCharacter } from '../services';
import { useRouter } from 'next/router';
import { useAuth } from '../hooks';
import Link from 'next/link';

const Admin = () => {
  const router = useRouter();
  const [error, setError] = useState(null);
  const [character, setCharacter] = useState('');
  const [file, setFile] = useState<string | File>('');
  useAuth();

  const uploadHandler = async () => {
    const data = new FormData();
    data.append('name', character);
    data.append('image', file);

    try {
      await createCharacter(data);
      router.push('/');
    } catch (error: any) {
      setError(error.message);
    }
  };

  return (
    <div>
      <Head>
        <title>God of War - Ragnarök!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <main className='flex justify-center items-center pt-4 flex-col'>
        <Link href={'/'} className='fixed top-6 left-6 p-2 transition-all hover:bg-gray-400 rounded-full bg-gray-300'>
          <svg
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'
          >
            <path
              d='M9.57 5.93005L3.5 12.0001L9.57 18.0701'
              stroke='#292D32'
              stroke-width='1.5'
              stroke-miterlimit='10'
              stroke-linecap='round'
              stroke-linejoin='round'
            />
            <path
              d='M20.4999 12H3.66992'
              stroke='#292D32'
              stroke-width='1.5'
              stroke-miterlimit='10'
              stroke-linecap='round'
              stroke-linejoin='round'
            />
          </svg>
        </Link>
        <h1 className='text-white text-center text-4xl mb-10'>
          God of war - Ragnarök!
        </h1>
        <div className='grid grid-cols-1 gap-10 pb-10'>
          <div className='bg-white rounded-lg shadow-lg p-4 w-96 h-60'>
            <input
              type='text'
              placeholder='Character'
              className='bg-gray-100 rounded-lg w-full py-3 mb-4 pl-4'
              onChange={(e) => setCharacter(e.target.value)}
            />

            <input
              type='file'
              className='bg-gray-100 rounded-lg w-full py-3 mb-4 pl-4'
              onChange={(e) => setFile(e.target.files![0])}
            />

            <button
              className='bg-red-500 text-white rounded-lg w-full py-3 mb-4'
              onClick={uploadHandler}
            >
              Upload
            </button>

            {error && (
              <span className='text-red-500 text-center inline-block w-full'>
                {error}
              </span>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Admin;
