import React, {useState} from "react";  
import Head from 'next/head'
import {createCharacter} from '../services'
import {useRouter} from 'next/router'
import {useAuth} from '../hooks'

const Admin = () => {
    const router = useRouter();
    const [error, setError] = useState(null);
    const [character, setCharacter] = useState('');
    const [file, setFile] = useState('');
    useAuth();

    const uploadHandler = async () => {
        const data = new FormData();
        data.append('name', character);
        data.append('image', file);

        try {
            await createCharacter(data);
            router.push('/');
        } catch (error) {
            setError(error.message);
        }
    }

    return (
        <div>
        <Head>
          <title>God of War - Ragnarök!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
  
        <main className='flex justify-center items-center pt-4 flex-col'>
          <h1 className='text-white text-center text-4xl mb-10'>God of war - Ragnarök!</h1>
          <div className='grid grid-cols-1 gap-10 pb-10'>
            <div className='bg-white rounded-lg shadow-lg p-4 w-96 h-60'>
                <input 
                    type="text" 
                    placeholder="Character" 
                    className='bg-gray-100 rounded-lg w-full h-12 mb-4 pl-4' 
                    onChange={e => setCharacter(e.target.value)} 
                />
                
                <input 
                    type="file" 
                    className='bg-gray-100 rounded-lg w-full h-12 mb-4 pl-4' 
                    onChange={e => setFile(e.target.files[0])} 
                />

                <button className='bg-red-500 text-white rounded-lg w-full h-12 mb-4' onClick={uploadHandler}>Upload</button>

                {error && <span className='text-red-500 text-center inline-block w-full'>{error}</span>}
            </div>
          </div>
        </main>
      </div>
    );
}

export default Admin;