import Head from 'next/head'
import { useEffect, useState } from 'react'
import Character from '../components/Character'
import {getCharacters, logout} from '../services'
import {useAuth} from '../hooks'

type Character = {
  id: number
  name: string
  image: string
  likes: number
}

export default function Home() {
  const [characters, setCharacters] = useState<Character[]>([]);
  const user = useAuth();
  
  useEffect(() => {
    (async () => {
      const { data } = await getCharacters();
      setCharacters(data);
    })();
  }, []);

  const logoutHandler = async () => {
    await logout();
    window.location.reload();
  }

  return (
    <div>
      <Head>
        <title>God of War - Ragnarök!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className='flex justify-center items-center pt-4 flex-col'>
        <div className='flex justify-between items-center w-full mb-10 px-10'>
          <div></div>
          <h1 className='text-white text-center text-4xl'>God of war - Ragnarök!</h1>
           {user 
              ? (<div>
                  <a href='/admin' className='text-white hover:text-purple-400 mr-4' >Admin</a>
                <button className='text-white hover:text-purple-400' onClick={logoutHandler}>Logout</button>
              </div>)
              : <a href='/login' className='text-white hover:text-purple-400' >Login</a>
            }
        </div>
        <div className='grid grid-cols-2 gap-10 pb-10'>
          {
            characters.map(({id, name, image, likes}) => (
              <Character key={id} name={name} image={image} likes={likes} />
            )) 
          }
        </div>
      </main>
    </div>
  )
}