import Head from 'next/head'
import Character from '../components/Character'
import axios from 'axios'

type Character = {
  id: number
  name: string
  image: string
  likes: number
}

export default function Home({data}: {data: Character[]}) {
  return (
    <div>
      <Head>
        <title>God of War - Ragnarök!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className='flex justify-center items-center pt-4 flex-col'>
        <h1 className='text-white text-center text-4xl mb-10'>God of war - Ragnarök!</h1>
        <div className='grid grid-cols-2 gap-10 pb-10'>
          {
            data.map(({id, name, image, likes}) => (
              <Character key={id} name={name} image={image} likes={likes} />
            )) 
          }
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const { data } = await axios.get(`${process.env.APP_URL}/characters`)
  return {
    props: {
      data,
    },
  };
}